// Generated by CoffeeScript 1.6.3
var Api;

Api = (function() {
  function Api() {}

  Api.name_spaces = {
    Led: require("./bb_led"),
    Dsc: require("./stepper").create()
  };

  Api.exec = function(name_space, method, params) {
    return Api.name_spaces[name_space][method].apply(void 0, params);
  };

  return Api;

}).call(this);

module.exports = {
  name_spaces: Api.name_spaces,
  exec: Api.exec
};
