// Generated by CoffeeScript 1.6.3
var Config;

Config = (function() {
  function Config() {}

  Config.init = function() {
    console.log("Config.init...");
    Config.sh = require("execSync");
    return Config.determine_emulated();
  };

  Config.determine_emulated = function() {
    Config.os = Config.sh.exec("uname").stdout.trim();
    Config.emulated = Config.os.match(/darwin/i) ? true : false;
    return console.log("Config.emulated = " + Config.emulated + " | (os = " + Config.os + ")");
  };

  return Config;

}).call(this);

Config.init();

module.exports = {
  Config: Config,
  emulated: Config.emulated
};
