// Generated by CoffeeScript 1.6.3
var config, fs, sync_write;

fs = require("fs");

config = require("./config");

sync_write = function(path, text) {
  var write_buffer,
    _this = this;
  console.log("rw.write: writing - path: " + path + " | text:" + text);
  if (config.emulated) {
    console.log("RW.sync_write: Not writing becuase Config.emulated = true");
    return;
  }
  try {
    write_buffer = new Buffer(text);
  } catch (_error) {
    debugger;
  }
  return fs.open(path, 'w', function(err, fd) {
    var bytes;
    if (err) {
      throw err;
    }
    bytes = fs.writeSync(fd, write_buffer, 0, write_buffer.length, null);
    return console.log("rw.write: wrote - path: " + path + " | text:" + text + " | " + bytes + " bytes");
  });
};

module.exports = {
  sync_write: sync_write
};
