// Generated by CoffeeScript 1.6.3
var emulated, fs, set_emulated, sync_write;

fs = require("fs");

emulated = false;

set_emulated = function(val) {
  return emulated = val;
};

sync_write = function(path, text) {
  var write_buffer,
    _this = this;
  console.log("rw.write: writing - path: " + path + " | text:" + text);
  if (emulated) {
    return;
  }
  try {
    write_buffer = new Buffer(text);
  } catch (_error) {
    debugger;
  }
  return fs.open(path, 'w', function(err, fd) {
    var bytes;
    if (err) {
      throw err;
    }
    bytes = fs.writeSync(fd, write_buffer, 0, write_buffer.length, null);
    return console.log("rw.write: wrote - path: " + path + " | text:" + text + " | " + bytes + " bytes");
  });
};

module.exports = {
  sync_write: sync_write,
  set_emulated: set_emulated
};
