// Generated by CoffeeScript 1.6.3
var SocketIO;

SocketIO = (function() {
  function SocketIO() {}

  SocketIO.init = function() {
    SocketIO.port = 4000;
    SocketIO.app = require('http').createServer();
    SocketIO.io = require('socket.io').listen(SocketIO.app);
    SocketIO.io.set('log level', 1);
    SocketIO.app.listen(SocketIO.port);
    SocketIO.setup_socket_listener();
    return SocketIO.api = require("./api");
  };

  SocketIO.setup_socket_listener = function() {
    return SocketIO.io.sockets.on('connection', function(socket) {
      SocketIO.socket = socket;
      socket.emit('connected', {
        port: SocketIO.port
      });
      return socket.on('Api', function(data) {
        return SocketIO.handle_api(data);
      });
    });
  };

  SocketIO.handle_api = function(data) {
    var callback;
    callback = function(cb_params) {
      return SocketIO.transmit_callback(data.callback_id, cb_params);
    };
    data.params.push(callback);
    return SocketIO.api.exec(data.name_space, data.method, data.params);
  };

  SocketIO.transmit_callback = function(callback_id, params) {
    console.log("SocketIO.transmit_callback: called with callback_id = " + callback_id);
    return SocketIO.socket.emit("callback", {
      callback_id: callback_id,
      params: params
    });
  };

  return SocketIO;

}).call(this);

module.exports = {
  socket_io: SocketIO,
  init: SocketIO.init
};
